In [ ]:
# %matplotlib widget
import sys, os, importlib
package_path = os.path.abspath('..')    
if package_path not in sys.path:
    sys.path.append(package_path)
from package import functions as fn
from package import model as rm
from package import optimizer as opt
from package import plots
import numpy as np
from obspy.taup import TauPyModel

In [ ]:
# VERIFYING FORWARD SIMULATIONS
solutions = radiation_model.get_optimal_iterates()
outcomes = [radiation_model(params, return_A=True) for params in solutions]
model_Ao = radiation_model.get_Ao()
similarities = [fn.unit_vec(model_Ao) @ fn.unit_vec(outcomes[i]) for i in range(len(outcomes))]
print(max(similarities), min(similarities))

In [ ]:
# # OMKAR COMPARISON

# def Rpattern(fault, azimuth, takeoff_angles, alpha_beta: list = []): # Update Omkar on incidence -> takeoff
#     """
#     Calculate predicted amplitudes of P, SV, and SH waves.
#     IN: fault = [strike, dip, rake]
#              = faulting mechanism, described by a list of strike, dip, and rake
#              (note, strike is measured clockwise from N, dip is measured positive downwards
#              (between 0 and 90) w.r.t. a horizontal that is 90 degrees clockwise from strike,
#              and rake is measured positive upwards (counterclockwise)
#         azimuth: azimuth with which ray path leaves source (clockwise from N)
#         takeoff_angles = [i, j]
#               i = angle between P ray path & vertical in the source model layer
#               j = angle between S ray path & vertical in the source model layer
#     OUT: Amplitudes for P, SV, and SH waves
#     P as measured on L (~Z) component, SV measured on Q (~R) component, and SH measured on T component.
#     All input is in degrees. 
#     (c) 2020 Suzan van der Lee
#     """

#     strike, dip, rake = fault
#     rela = strike - azimuth
#     sinlam = np.sin(np.radians(rake))
#     coslam = np.cos(np.radians(rake))
#     sind = np.sin(np.radians(dip))
#     cosd = np.cos(np.radians(dip))
#     cos2d = np.cos(np.radians(2*dip))
#     sinrela = np.sin(np.radians(rela))
#     cosrela = np.cos(np.radians(rela))
#     sin2rela = np.sin(np.radians(2*rela))
#     cos2rela = np.cos(np.radians(2*rela))

#     sR = sinlam*sind*cosd
#     qR = sinlam*cos2d*sinrela + coslam*cosd*cosrela
#     pR = coslam*sind*sin2rela - sinlam*sind*cosd*cos2rela
#     pL = sinlam*sind*cosd*sin2rela + coslam*sind*cos2rela
#     qL = -coslam*cosd*sinrela + sinlam*cos2d*cosrela

#     iP = np.radians(takeoff_angles[0])
#     jS = np.radians(takeoff_angles[1])

#     AP = sR*(3*np.cos(iP)**2 - 1) - qR*np.sin(2*iP) - pR*np.sin(iP)**2
#     ASV = 1.5*sR*np.sin(2*jS) + qR*np.cos(2*jS) + 0.5*pR*np.sin(2*jS)
#     ASH = qL*np.cos(jS) + pL*np.sin(jS)
    
#     # Incorporating b3_over_a3
#     if len(alpha_beta) != 0:
#         AP /= alpha_beta[0]**3
#         ASV /= alpha_beta[1]**3
#         ASH /= alpha_beta[1]**3

#     return np.array([AP,ASV,ASH])


# comp_outcomes = [Rpattern(np.rad2deg(params),
#                           azimuth, takeoff_angles,
#                           alpha_beta=velocities) for params in solutions]
# similarities_comp = [fn.unit_vec(model_Ao) @ fn.unit_vec(comp_outcomes[i])
#                      for i in range(len(comp_outcomes))]
# print(max(similarities_comp), min(similarities_comp))

In [1]:
import numpy as np

#demo that pinv = inv for square full rank matrices
A = np.array([[1,2,3],[0,1,4],[5,6,0]])
A_pinv = np.linalg.pinv(A)
A_inv = np.linalg.inv(A)
print(A_pinv)
print(A_inv)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
